INSERT INTO CLIENTE (NOME, SOBRENOME, EMAIL, SENHA) VALUES ('JOAO', 'DA SILVA', 'JOAODASILVA@GMAIL.COM', '123456');
INSERT INTO EVENTO (NOME, DATA, PRECO, ENDERECO, CEP, NUMERO, BAIRRO, CIDADE, ESTADO, PAIS) 
VALUES ('FESTANCA DA MENTIRA', '2019/04/01 00:00', 0.00, 'RUA DOS BOBOS', '355000-000', 0, 'LIBERDADE', 'QUALQUER LUGAR', 'MINAS GERAIS',
	'BRASIL');
INSERT INTO ACAOHISTORICO (DESCRICAO) VALUES ('CRIACAO');
INSERT INTO ACAOHISTORICO (DESCRICAO) VALUES ('COMPARECIMENTO');
INSERT INTO ACAOHISTORICO (DESCRICAO) VALUES ('EXCLUSAO');

